### ISSUE TITLE
Gurobi not recognized with environment.

### ISSUE THREAD

**Issue by blegat** [lanl-ansi/Alpine.jl#186] opened 2022-03-04 15:58 UTC
```julia
GRB_ENV = Gurobi.Env()
solver = optimizer_with_attributes(
    Alpine.Optimizer,
    "nlp_solver" => Ipopt.Optimizer,
    "mip_solver" => () -> Gurobi.Optimizer(GRB_ENV),
)
model = Model(solver)
# ...
optimize!(model)
```
gives
```
ERROR: LoadError: Unsupported MIP solver #29; use a Alpine-supported MIP solver
```

**Comment by odow** [comment] 2022-03-15 01:06
Closing as duplicate of #178

**Closed by odow** 2022-03-15 01:06 UTC
Labels: bug
